Upgrade Metabase to v0.51 (#60)

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -18,7 +18,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: metabase/metabase
-          ref: v0.50.10
+          ref: v0.51.11
 
       - name: Checkout Driver Repo
         uses: actions/checkout@v3
@@ -74,7 +74,24 @@ jobs:
         run: |
           mkdir -p /home/runner/.config/clojure
           cat modules/drivers/materialize/.github/deps.edn | sed -e "s|PWD|$PWD|g" > /home/runner/.config/clojure/deps.edn
-          DRIVERS=materialize clojure -X:dev:drivers:drivers-dev:test:user/materialize
+
+          # Retry tests up to 2 times as the Metabase test data sometimes fails to load on the first try
+          ATTEMPTS=0
+          MAX_RETRIES=2
+
+          until [ $ATTEMPTS -ge $MAX_RETRIES ]
+          do
+            echo "Attempt $(($ATTEMPTS + 1)) of $MAX_RETRIES..."
+            DRIVERS=materialize clojure -X:dev:drivers:drivers-dev:test:user/materialize && break
+            ATTEMPTS=$(($ATTEMPTS + 1))
+            echo "Tests failed. Retrying in 10 seconds..."
+            sleep 10
+          done
+
+          if [ $ATTEMPTS -eq $MAX_RETRIES ]; then
+            echo "Tests failed after $MAX_RETRIES attempts."
+            exit 1
+          fi
 
       - name: Build Materialize driver
         run: |
